bash train/2dgs/_.sh bicycle
bash train/2dgs/_.sh bonsai
bash train/2dgs/_.sh counter
bash train/2dgs/_.sh flowers
bash train/2dgs/_.sh garden
bash train/2dgs/_.sh kitchen
bash train/2dgs/_.sh room
bash train/2dgs/_.sh stump
bash train/2dgs/_.sh treehill