bash train/tgs/_.sh bicycle
bash train/tgs/_.sh bonsai
bash train/tgs/_.sh counter
bash train/tgs/_.sh flowers
bash train/tgs/_.sh garden
bash train/tgs/_.sh kitchen
bash train/tgs/_.sh room
bash train/tgs/_.sh stump
bash train/tgs/_.sh treehill